Survey Form.
m00h0/Survey-Form pull request #1
Opened 2023-06-12 08:06 UTC by AhmedMh0

2023-06-12 08:18 UTC, AhmedMh0 commented
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



To Highlight 🥇
✅ Descriptive Pull Request title and summary. 
✅ Good use of Github flow 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

Changes Required
 Please check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏


- the link to your image is broken can you fix it please.

- you need linter files in your project so you can check linters.

- your pull request wasn't a professional title and description.

you haven't  GitHub flow method used.

The project isn't professionally documented.

2023-06-12 08:27 UTC, wayungi requested changes
Hi @AhmedMh0 , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Reviews given. ✔️ 



## Required Changes ♻️
_Check the comments under the review._
- [ ] Please use GitHub inline comments to perform the review. This means you should write in the line that you request the code to be changed/ improved. Kindly take a look at this [guide](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) and apply the concepts therein to your code reviews.

- [ ] Please make sure your comments are clear, polite and offer reasons why you what the code changed.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 08:00 UTC, AhmedMh0 reviewed
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🥇
✅ Descriptive Pull Request title and summary.
✅ Good use of Github flow
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

Changes Required
Please check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

- the link to your image is broken can you fix it please.

- you need linter files in your project so you can check linters.

- your pull request wasn't a professional title and description.

- you haven't GitHub flow method used.

- The project isn't professionally documented.





- [ ]  Please check the comments under the review

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @AhmedMh0  ) in your question so I can receive the notification.

2023-06-13 08:00 UTC, m00h0 commented on style.css
> +    url(https://avic.uobaghdad.edu.iq/wp-content/uploads/sites/54/2020/11/%D8%B5%D9%88%D8%B1%D8%A9-%D9%84%D9%8A%D9%84%D9%8A%D8%A3.png);
Your link to the image is broken try to change it.

2023-06-13 08:16 UTC, LionRouge1 requested changes
Hi @AhmedMh0, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 
- [ ] As requested by the previous reviewer, Kindly make sure your comments are polite and give a reason why you suggested the changes

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-14 09:16 UTC, Strangeal approved these changes
Hi @AhmedMh0, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 09:26 UTC, merged